using Microsoft.EntityFrameworkCore;
using SaleStore.Models;
using SaleStore.Services;

namespace SaleStore.Data
{
    public static class AuthDbInitializer
    {
        public static async Task EnsureCreatedAsync(ApplicationDbContext context, PasswordHasher passwordHasher)
        {
            const string createUsersTable = @"
                CREATE TABLE IF NOT EXISTS app_users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(50) NOT NULL,
                    full_name VARCHAR(120) NOT NULL,
                    email VARCHAR(180) NOT NULL,
                    phone VARCHAR(30) NULL,
                    password_hash TEXT NOT NULL,
                    password_salt TEXT NOT NULL,
                    role VARCHAR(20) NOT NULL DEFAULT 'User',
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NULL,
                    last_login_at TIMESTAMPTZ NULL
                );";

            const string createUsersEmailIndex = @"
                CREATE UNIQUE INDEX IF NOT EXISTS ix_app_users_email
                ON app_users (LOWER(email));";

            const string createUsersUsernameIndex = @"
                CREATE UNIQUE INDEX IF NOT EXISTS ix_app_users_username
                ON app_users (LOWER(username));";

            const string addUsernameColumn = @"
                ALTER TABLE app_users
                ADD COLUMN IF NOT EXISTS username VARCHAR(50);";

            const string addRoleColumn = @"
                ALTER TABLE app_users
                ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'User';";

            const string fillMissingUsernames = @"
                UPDATE app_users
                SET username = split_part(email, '@', 1)
                WHERE username IS NULL OR btrim(username) = '';";

            const string fillMissingRoles = @"
                UPDATE app_users
                SET role = 'User'
                WHERE role IS NULL OR btrim(role) = '';";

            const string createActivitiesTable = @"
                CREATE TABLE IF NOT EXISTS auth_activities (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
                    activity_type VARCHAR(32) NOT NULL,
                    ip_address VARCHAR(64) NULL,
                    user_agent VARCHAR(512) NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );";

            const string createActivitiesIndex = @"
                CREATE INDEX IF NOT EXISTS ix_auth_activities_user_created_at
                ON auth_activities (user_id, created_at DESC);";

            const string addCreatedByUserIdColumn = @"
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT NULL;";

            const string createOrdersCreatedByIndex = @"
                CREATE INDEX IF NOT EXISTS ix_orders_created_by_user_id
                ON orders (created_by_user_id);";

            await context.Database.ExecuteSqlRawAsync(createUsersTable);
            await context.Database.ExecuteSqlRawAsync(addUsernameColumn);
            await context.Database.ExecuteSqlRawAsync(addRoleColumn);
            await context.Database.ExecuteSqlRawAsync(fillMissingUsernames);
            await context.Database.ExecuteSqlRawAsync(fillMissingRoles);
            await context.Database.ExecuteSqlRawAsync(createUsersEmailIndex);
            await context.Database.ExecuteSqlRawAsync(createUsersUsernameIndex);
            await context.Database.ExecuteSqlRawAsync(createActivitiesTable);
            await context.Database.ExecuteSqlRawAsync(createActivitiesIndex);
            await context.Database.ExecuteSqlRawAsync(addCreatedByUserIdColumn);
            await context.Database.ExecuteSqlRawAsync(createOrdersCreatedByIndex);

            var adminExists = await context.AppUsers.AnyAsync(x => x.Username == "admin");
            if (!adminExists)
            {
                var (hash, salt) = passwordHasher.CreateHash("123");
                context.AppUsers.Add(new AppUser
                {
                    Username = "admin",
                    FullName = "System Admin",
                    Email = "admin@salestore.local",
                    PasswordHash = hash,
                    PasswordSalt = salt,
                    Role = AppRoles.Admin,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                });

                await context.SaveChangesAsync();
            }
        }
    }
}