using Microsoft.EntityFrameworkCore;
using SaleStore.Models;
using SaleStore.Services;

namespace SaleStore.Data
{
    public static class AuthDbInitializer
    {
        public static async Task EnsureCreatedAsync(ApplicationDbContext context, PasswordHasher passwordHasher)
        {
            const string createUsersTable = @"
                CREATE TABLE IF NOT EXISTS app_users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(50) NOT NULL,
                    full_name VARCHAR(120) NOT NULL,
                    email VARCHAR(180) NOT NULL,
                    phone VARCHAR(30) NULL,
                    password_hash TEXT NOT NULL,
                    password_salt TEXT NOT NULL,
                    role VARCHAR(20) NOT NULL DEFAULT 'User',
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NULL,
                    last_login_at TIMESTAMPTZ NULL
                );";

            const string createUsersEmailIndex = @"
                CREATE UNIQUE INDEX IF NOT EXISTS ix_app_users_email
                ON app_users (LOWER(email));";

            const string createUsersUsernameIndex = @"
                CREATE UNIQUE INDEX IF NOT EXISTS ix_app_users_username
                ON app_users (LOWER(username));";

            const string addUsernameColumn = @"
                ALTER TABLE app_users
                ADD COLUMN IF NOT EXISTS username VARCHAR(50);";

            const string addRoleColumn = @"
                ALTER TABLE app_users
                ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'User';";

            const string fillMissingUsernames = @"
                UPDATE app_users
                SET username = split_part(email, '@', 1)
                WHERE username IS NULL OR btrim(username) = '';";

            const string fillMissingRoles = @"
                UPDATE app_users
                SET role = 'User'
                WHERE role IS NULL OR btrim(role) = '';";

            const string createActivitiesTable = @"
                CREATE TABLE IF NOT EXISTS auth_activities (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
                    activity_type VARCHAR(32) NOT NULL,
                    ip_address VARCHAR(64) NULL,
                    user_agent VARCHAR(512) NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );";

            const string createActivitiesIndex = @"
                CREATE INDEX IF NOT EXISTS ix_auth_activities_user_created_at
                ON auth_activities (user_id, created_at DESC);";

            const string addCreatedByUserIdColumn = @"
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT NULL;";

            const string createOrdersCreatedByIndex = @"
                CREATE INDEX IF NOT EXISTS ix_orders_created_by_user_id
                ON orders (created_by_user_id);";

            const string addOrderCustomerNameColumn = @"
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS customer_name VARCHAR(120) NULL;";

            const string addOrderTableNumberColumn = @"
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS table_number VARCHAR(20) NULL;";
            
            const string addOrderPaymentMethodColumn = @"
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50) NULL;";

            const string addOrderIsPaidColumn = @"
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS is_paid BOOLEAN NOT NULL DEFAULT FALSE;";

            const string addOrderTransactionIdColumn = @"
                ALTER TABLE orders
                ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(100) NULL;";

            const string createReviewsTable = @"
                CREATE TABLE IF NOT EXISTS reviews (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
                    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
                    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
                    comment VARCHAR(1000) NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );";

            const string createReviewsIndex = @"
                CREATE INDEX IF NOT EXISTS ix_reviews_product_id
                ON reviews (product_id);";

            const string dropReviewsUniqueIndex = @"
                DROP INDEX IF EXISTS ix_reviews_product_user;";

            const string createReviewsUserIndex = @"
                CREATE INDEX IF NOT EXISTS ix_reviews_user_id
                ON reviews (user_id);";

            const string createUserCartItemsTable = @"
                CREATE TABLE IF NOT EXISTS user_cart_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
                    product_id INT NOT NULL,
                    product_name TEXT NOT NULL DEFAULT '',
                    price NUMERIC NOT NULL DEFAULT 0,
                    quantity INT NOT NULL DEFAULT 1,
                    image_url TEXT NULL,
                    category TEXT NULL,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );";

            const string createUserCartItemsIndex = @"
                CREATE UNIQUE INDEX IF NOT EXISTS ix_user_cart_items_user_product
                ON user_cart_items (user_id, product_id);";

            var allTablesSql = createUsersTable + addUsernameColumn + addRoleColumn + createUsersEmailIndex + createUsersUsernameIndex +
                               createActivitiesTable + createActivitiesIndex + addCreatedByUserIdColumn + createOrdersCreatedByIndex +
                               addOrderCustomerNameColumn + addOrderTableNumberColumn + addOrderPaymentMethodColumn + addOrderIsPaidColumn +
                               addOrderTransactionIdColumn + createReviewsTable + createReviewsIndex +
                               dropReviewsUniqueIndex + createReviewsUserIndex +
                               createUserCartItemsTable + createUserCartItemsIndex;

            await context.Database.ExecuteSqlRawAsync(allTablesSql);
            await context.Database.ExecuteSqlRawAsync(fillMissingUsernames);
            await context.Database.ExecuteSqlRawAsync(fillMissingRoles);

            var adminExists = await context.AppUsers.AnyAsync(x => x.Username == "admin");
            if (!adminExists)
            {
                var (hash, salt) = passwordHasher.CreateHash("123");
                context.AppUsers.Add(new AppUser
                {
                    Username = "admin",
                    FullName = "System Admin",
                    Email = "admin@salestore.local",
                    PasswordHash = hash,
                    PasswordSalt = salt,
                    Role = AppRoles.Admin,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow
                });

                await context.SaveChangesAsync();
            }

            // Seed sản phẩm "Trà & Khác" nếu chưa có
            var hasTeaProducts = await context.Products.AnyAsync(p => p.Category == "Trà & Khác");
            if (!hasTeaProducts)
            {
                var teaProducts = new[]
                {
                    new Product
                    {
                        Name = "Trà Sen Vàng",
                        Description = "Trà ướp hương sen thanh mát, vị ngọt nhẹ tự nhiên — thức uống truyền thống Việt Nam.",
                        Price = 45000,
                        Category = "Trà & Khác",
                        ImageUrl = "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600&h=400&fit=crop",
                        Stock = 100,
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow,
                        UpdatedAt = DateTime.UtcNow
                    },
                    new Product
                    {
                        Name = "Trà Đào Cam Sả",
                        Description = "Trà đào kết hợp cam tươi và sả thơm, tươi mát cho ngày nắng.",
                        Price = 50000,
                        Category = "Trà & Khác",
                        ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&h=400&fit=crop",
                        Stock = 80,
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow,
                        UpdatedAt = DateTime.UtcNow
                    },
                    new Product
                    {
                        Name = "Trà Matcha Latte",
                        Description = "Matcha Nhật Bản nguyên chất kết hợp sữa tươi, béo ngậy và thơm dịu.",
                        Price = 55000,
                        Category = "Trà & Khác",
                        ImageUrl = "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=600&h=400&fit=crop",
                        Stock = 60,
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow,
                        UpdatedAt = DateTime.UtcNow
                    },
                    new Product
                    {
                        Name = "Nước Ép Cam Tươi",
                        Description = "Cam vắt tươi 100%, không thêm đường — bổ sung vitamin C tự nhiên.",
                        Price = 40000,
                        Category = "Trà & Khác",
                        ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&h=400&fit=crop",
                        Stock = 50,
                        IsActive = true,
                        CreatedAt = DateTime.UtcNow,
                        UpdatedAt = DateTime.UtcNow
                    }
                };

                context.Products.AddRange(teaProducts);
                await context.SaveChangesAsync();
            }
        }
    }
}